spring.application.name=Finance_Backend

server.port=8089

spring.mongodb.uri=mongodb+srv://hmsdbuser:hmsdb123@cluster0.1j352.mongodb.net/Financedb?retryWrites=true&w=majority

app.jwt.secret=kjerhjnrghfkewjfrehiejrklehhgkfn
app.jwt.expiration-ms=86400000