spring.application.name=Finance_Backend

server.port=8089

spring.mongodb.uri=mongodb+srv://hmsdbuser:hmsdb123@cluster0.1j352.mongodb.net/financedb?retryWrites=true&w=majority
spring.autoconfigure.exclude=org.springframework